/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_jni_FirstJni */

#ifndef _Included_com_example_administrator_jni_FirstJni
#define _Included_com_example_administrator_jni_FirstJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_jni_FirstJni
 * Method:    get
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_com_example_administrator_jni_FirstJni_get
  (JNIEnv *, jobject);

/*
 * Class:     com_example_administrator_jni_FirstJni
 * Method:    set
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_com_example_administrator_jni_FirstJni_set
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
